// Swedish sentences for spaced repetition
// Each sentence has:
//   id       – unique string
//   sv       – Swedish text
//   en       – English translation
//   wordIds  – word IDs (from WORDS) that must ALL have an sm2State entry before this unlocks
//   clozeId  – the word ID to blank out for cloze cards (pick the most meaningful content word)

const SENTENCES = [
  // ── Tier 1: unlocks after seeing words 1-30 ───────────────────────────────
  { id: 's001', sv: 'Jag är här.',            en: 'I am here.',                    wordIds: [1, 3, 19],        clozeId: 19  },
  { id: 's002', sv: 'Det är bra.',            en: "That's good.",                  wordIds: [2, 3, 51],        clozeId: 51  },
  { id: 's003', sv: 'Jag vet inte.',          en: "I don't know.",                 wordIds: [1, 36, 5],        clozeId: 36  },
  { id: 's004', sv: 'Vad är det?',            en: 'What is that?',                 wordIds: [15, 3, 2],        clozeId: 15  },
  { id: 's005', sv: 'Ja, det är bra.',        en: "Yes, that's good.",             wordIds: [35, 2, 3, 51],    clozeId: 51  },
  { id: 's006', sv: 'Nej, inte nu.',          en: 'No, not now.',                  wordIds: [37, 5, 34],       clozeId: 34  },
  { id: 's007', sv: 'Tack så mycket.',        en: 'Thank you very much.',          wordIds: [72, 24, 83],      clozeId: 72  },
  { id: 's008', sv: 'Jag vill ha det.',       en: 'I want that.',                  wordIds: [1, 33, 53, 2],    clozeId: 33  },
  { id: 's009', sv: 'Kan du höra mig?',       en: 'Can you hear me?',              wordIds: [26, 4, 17],       clozeId: 26  },
  { id: 's010', sv: 'Han är inte här.',       en: "He isn't here.",                wordIds: [14, 3, 5, 19],    clozeId: 14  },
  { id: 's011', sv: 'Vi ska gå nu.',          en: "We're going now.",              wordIds: [10, 29, 73, 34],  clozeId: 73  },
  { id: 's012', sv: 'Vad vill du ha?',        en: 'What do you want?',             wordIds: [15, 33, 4, 53],   clozeId: 33  },
  { id: 's013', sv: 'Det är inte sant.',      en: "That's not true.",              wordIds: [2, 3, 5],         clozeId: 3   },
  { id: 's014', sv: 'Jag ska göra det.',      en: "I'll do it.",                   wordIds: [1, 29, 61, 2],    clozeId: 61  },
  { id: 's015', sv: 'Hon är här nu.',         en: "She's here now.",               wordIds: [39, 3, 19, 34],   clozeId: 39  },
  { id: 's016', sv: 'Vad ska vi göra?',       en: 'What are we going to do?',      wordIds: [15, 29, 10, 61],  clozeId: 61  },
  { id: 's017', sv: 'Jag har det.',           en: 'I have it.',                    wordIds: [1, 9, 2],         clozeId: 9   },
  { id: 's018', sv: 'Du kan göra det.',       en: 'You can do it.',                wordIds: [4, 26, 61, 2],    clozeId: 26  },
  { id: 's019', sv: 'Det är inte för mig.',   en: "It's not for me.",              wordIds: [2, 3, 5, 13, 17], clozeId: 13  },
  { id: 's020', sv: 'Jag vet vad du vill.',   en: 'I know what you want.',         wordIds: [1, 36, 15, 4, 33],clozeId: 36  },

  // ── Tier 2: unlocks after seeing words 1-60 ───────────────────────────────
  { id: 's021', sv: 'Han kan inte se dig.',   en: "He can't see you.",             wordIds: [14, 26, 5, 78, 21],  clozeId: 78  },
  { id: 's022', sv: 'Vi måste gå ut.',        en: 'We have to go out.',            wordIds: [10, 46, 73, 56],     clozeId: 46  },
  { id: 's023', sv: 'Jag vill inte vara här.',en: "I don't want to be here.",      wordIds: [1, 33, 5, 59, 19],   clozeId: 33  },
  { id: 's024', sv: 'Det kan vara bra.',      en: 'It could be good.',             wordIds: [2, 26, 59, 51],      clozeId: 51  },
  { id: 's025', sv: 'Kom hit!',               en: 'Come here!',                    wordIds: [47, 129],            clozeId: 47  },
  { id: 's026', sv: 'Vad gör du?',            en: 'What are you doing?',           wordIds: [15, 45, 4],          clozeId: 45  },
  { id: 's027', sv: 'Jag förstår inte det.', en: "I don't understand that.",      wordIds: [1, 162, 5, 2],       clozeId: 162 },
  { id: 's028', sv: 'Hon ville ha det.',      en: 'She wanted it.',                wordIds: [39, 149, 53, 2],     clozeId: 149 },
  { id: 's029', sv: 'Det är allt.',           en: "That's all.",                   wordIds: [2, 3, 77],           clozeId: 77  },
  { id: 's030', sv: 'Kan jag få det?',        en: 'Can I have it?',                wordIds: [26, 1, 80, 2],       clozeId: 80  },
  { id: 's031', sv: 'Vi kan inte göra det.',  en: "We can't do that.",             wordIds: [10, 26, 5, 61, 2],   clozeId: 61  },
  { id: 's032', sv: 'Vem är du?',             en: 'Who are you?',                  wordIds: [84, 3, 4],           clozeId: 84  },
  { id: 's033', sv: 'Gå dit nu.',             en: 'Go there now.',                 wordIds: [73, 43, 34],         clozeId: 43  },
  { id: 's034', sv: 'Jag tror på dig.',       en: 'I believe in you.',             wordIds: [1, 68, 11, 21],      clozeId: 68  },
  { id: 's035', sv: 'Det var inte bra.',      en: "That wasn't good.",             wordIds: [2, 22, 5, 51],       clozeId: 51  },
  { id: 's036', sv: 'Han gör det igen.',      en: "He's doing it again.",          wordIds: [14, 45, 2, 70],      clozeId: 70  },
  { id: 's037', sv: 'Jag måste ta det.',      en: 'I have to take it.',            wordIds: [1, 46, 55, 2],       clozeId: 46  },
  { id: 's038', sv: 'Vi har inte det.',       en: "We don't have it.",             wordIds: [10, 9, 5, 2],        clozeId: 9   },
  { id: 's039', sv: 'Du ska se det.',         en: "You'll see it.",                wordIds: [4, 29, 78, 2],       clozeId: 78  },
  { id: 's040', sv: 'Vad säger du?',          en: 'What do you say?',              wordIds: [15, 107, 4],         clozeId: 107 },

  // ── Tier 3: unlocks after seeing words 1-100 ──────────────────────────────
  { id: 's041', sv: 'Jag kan bara göra det.', en: 'I can only do it.',            wordIds: [1, 26, 38, 61, 2],   clozeId: 38  },
  { id: 's042', sv: 'Det finns ingen här.',   en: "There's nobody here.",          wordIds: [2, 93, 79, 19],      clozeId: 79  },
  { id: 's043', sv: 'Han har aldrig gjort det.',en: "He's never done that.",       wordIds: [14, 9, 89, 147, 2],  clozeId: 89  },
  { id: 's044', sv: 'Du behöver inte göra det.',en: "You don't need to do that.", wordIds: [4, 92, 5, 61, 2],    clozeId: 92  },
  { id: 's045', sv: 'Kanske är det bra.',     en: 'Maybe that is good.',           wordIds: [90, 3, 2, 51],       clozeId: 90  },
  { id: 's046', sv: 'Jag tror inte det.',     en: "I don't think so.",             wordIds: [1, 68, 5, 2],        clozeId: 68  },
  { id: 's047', sv: 'Vad händer?',            en: 'What is happening?',            wordIds: [15, 192],            clozeId: 192 },
  { id: 's048', sv: 'Hur mår du?',            en: 'How are you?',                  wordIds: [41, 4],              clozeId: 41  },
  { id: 's049', sv: 'Det går bra.',           en: "It's going well.",              wordIds: [2, 85, 51],          clozeId: 85  },
  { id: 's050', sv: 'Vad vill du säga?',      en: 'What do you mean?',             wordIds: [15, 33, 4, 123],     clozeId: 123 },
  { id: 's051', sv: 'Jag ser dig inte.',      en: "I can't see you.",              wordIds: [1, 86, 21, 5],       clozeId: 86  },
  { id: 's052', sv: 'Var är han nu?',         en: 'Where is he now?',              wordIds: [19, 3, 14, 34],      clozeId: 14  },
  { id: 's053', sv: 'Det blir bättre.',       en: "It'll get better.",             wordIds: [2, 94, 184],         clozeId: 184 },
  { id: 's054', sv: 'Du måste stanna.',       en: 'You have to stay.',             wordIds: [4, 46, 209],         clozeId: 209 },
  { id: 's055', sv: 'Jag väntar på dig.',     en: "I'm waiting for you.",          wordIds: [1, 119, 11, 21],     clozeId: 119 },
  { id: 's056', sv: 'Kan vi prata?',          en: 'Can we talk?',                  wordIds: [26, 10, 158],        clozeId: 158 },
  { id: 's057', sv: 'Jag gillar det.',        en: 'I like it.',                    wordIds: [1, 173, 2],          clozeId: 173 },
  { id: 's058', sv: 'Det var länge sedan.',   en: 'That was a long time ago.',     wordIds: [2, 22, 206, 106],    clozeId: 206 },
  { id: 's059', sv: 'Vem sa det?',            en: 'Who said that?',                wordIds: [84, 71, 2],          clozeId: 71  },
  { id: 's060', sv: 'Jag är ledsen.',         en: "I'm sorry / I'm sad.",          wordIds: [1, 3, 208],          clozeId: 208 },

  // ── Tier 4: unlocks after seeing words 1-150 ──────────────────────────────
  { id: 's061', sv: 'Jag älskar dig.',        en: 'I love you.',                   wordIds: [1, 163, 21],         clozeId: 163 },
  { id: 's062', sv: 'Du har rätt.',           en: "You're right.",                 wordIds: [4, 9, 141],          clozeId: 141 },
  { id: 's063', sv: 'Det är fel.',            en: "That's wrong.",                 wordIds: [2, 3, 154],          clozeId: 154 },
  { id: 's064', sv: 'Jag tänker på dig.',     en: "I'm thinking of you.",          wordIds: [1, 180, 11, 21],     clozeId: 180 },
  { id: 's065', sv: 'Han kör bort.',          en: "He's driving away.",            wordIds: [14, 221, 176],       clozeId: 221 },
  { id: 's066', sv: 'Vi tittar på det.',      en: "We're watching it.",            wordIds: [10, 151, 11, 2],     clozeId: 151 },
  { id: 's067', sv: 'Det är min sak.',        en: "It's my thing.",                wordIds: [2, 3, 42, 226],      clozeId: 226 },
  { id: 's068', sv: 'Jag förlåter dig.',      en: 'I forgive you.',                wordIds: [1, 197, 21],         clozeId: 197 },
  { id: 's069', sv: 'Du ser bra ut.',         en: 'You look good.',                wordIds: [4, 86, 51, 56],      clozeId: 51  },
  { id: 's070', sv: 'Det är en bra dag.',     en: "It's a good day.",              wordIds: [2, 3, 7, 51, 152],   clozeId: 152 },
  { id: 's071', sv: 'Hon vet inte vem jag är.',en: "She doesn't know who I am.",   wordIds: [39, 36, 5, 84, 1, 3],clozeId: 84  },
  { id: 's072', sv: 'Vi pratar om det.',      en: "We're talking about it.",       wordIds: [10, 158, 20, 2],     clozeId: 158 },
  { id: 's073', sv: 'Jag hör dig.',           en: 'I hear you.',                   wordIds: [1, 181, 21],         clozeId: 181 },
  { id: 's074', sv: 'Livet är bra.',          en: 'Life is good.',                 wordIds: [160, 3, 51],         clozeId: 160 },
  { id: 's075', sv: 'Det är ditt problem.',   en: "That's your problem.",          wordIds: [2, 3, 48, 224],      clozeId: 224 },
  { id: 's076', sv: 'Jag tycker om dig.',     en: 'I like you.',                   wordIds: [1, 170, 20, 21],     clozeId: 170 },
  { id: 's077', sv: 'Hon gick hem.',          en: 'She went home.',                wordIds: [39, 189, 146],       clozeId: 146 },
  { id: 's078', sv: 'Det tar tid.',           en: 'It takes time.',                wordIds: [2, 102, 169],        clozeId: 169 },
  { id: 's079', sv: 'Vad heter du?',          en: 'What is your name?',            wordIds: [15, 207, 4],         clozeId: 207 },
  { id: 's080', sv: 'Jag heter Oliver.',      en: 'My name is Oliver.',            wordIds: [1, 207],             clozeId: 207 },

  // ── Tier 5: unlocks after seeing words 1-200 ──────────────────────────────
  { id: 's081', sv: 'Förlåt, jag förstår inte.', en: "Sorry, I don't understand.", wordIds: [197, 1, 162, 5],    clozeId: 162 },
  { id: 's082', sv: 'Ursäkta, var är toaletten?', en: 'Excuse me, where is the bathroom?', wordIds: [204, 19, 3], clozeId: 204 },
  { id: 's083', sv: 'Det finns ett problem.',  en: "There's a problem.",            wordIds: [2, 93, 30, 224],     clozeId: 224 },
  { id: 's084', sv: 'Jag behöver hjälp.',      en: 'I need help.',                  wordIds: [1, 92, 191],         clozeId: 191 },
  { id: 's085', sv: 'Snälla, hjälp mig.',      en: 'Please help me.',               wordIds: [205, 203, 17],       clozeId: 203 },
  { id: 's086', sv: 'Han berättar allt.',       en: 'He tells everything.',          wordIds: [14, 186, 77],        clozeId: 186 },
  { id: 's087', sv: 'Var är mina pengar?',      en: 'Where is my money?',            wordIds: [19, 3, 112, 200],    clozeId: 200 },
  { id: 's088', sv: 'Det händer igen.',         en: "It's happening again.",         wordIds: [2, 192, 70],         clozeId: 192 },
  { id: 's089', sv: 'Jag trodde du visste.',    en: 'I thought you knew.',           wordIds: [1, 172, 4, 195],     clozeId: 172 },
  { id: 's090', sv: 'Vad tycker du?',           en: 'What do you think?',            wordIds: [15, 170, 4],         clozeId: 170 },
  { id: 's091', sv: 'Det är ett sätt.',         en: "That's one way.",               wordIds: [2, 3, 30, 161],      clozeId: 161 },
  { id: 's092', sv: 'Jag är helt ledsen.',      en: "I'm truly sorry.",              wordIds: [1, 3, 198, 208],     clozeId: 208 },
  { id: 's093', sv: 'Vi ses morgon.',           en: "See you tomorrow.",             wordIds: [10, 78, 227],        clozeId: 227 },
  { id: 's094', sv: 'Det är precis rätt.',      en: "That's exactly right.",         wordIds: [2, 3, 174, 141],     clozeId: 141 },
  { id: 's095', sv: 'Han stod och väntade.',    en: 'He stood and waited.',          wordIds: [14, 214, 8, 119],    clozeId: 214 },
  { id: 's096', sv: 'Sluta nu.',                en: 'Stop now.',                     wordIds: [171, 34],            clozeId: 171 },
  { id: 's097', sv: 'Gå bort!',                 en: 'Go away!',                      wordIds: [73, 176],            clozeId: 176 },
  { id: 's098', sv: 'Håll inne med det.',       en: 'Keep it to yourself.',          wordIds: [219, 76, 16, 2],     clozeId: 219 },
  { id: 's099', sv: 'Jag gillar inte saker.',   en: "I don't like things.",          wordIds: [1, 173, 5, 215],     clozeId: 215 },
  { id: 's100', sv: 'Det är bättre utan dig.',  en: "It's better without you.",      wordIds: [2, 3, 184, 155, 21], clozeId: 184 },

  // ── Tier 6: phrases & conversational ──────────────────────────────────────
  { id: 's101', sv: 'God morgon!',              en: 'Good morning!',                 wordIds: [190, 227],           clozeId: 227 },
  { id: 's102', sv: 'Hur är det?',              en: 'How are things?',               wordIds: [41, 3, 2],           clozeId: 41  },
  { id: 's103', sv: 'Jag mår bra, tack.',       en: "I'm fine, thanks.",             wordIds: [1, 51, 72],          clozeId: 51  },
  { id: 's104', sv: 'Vad har du gjort idag?',   en: 'What have you done today?',     wordIds: [15, 9, 4, 147],      clozeId: 147 },
  { id: 's105', sv: 'Det vet jag inte.',        en: "I don't know that.",            wordIds: [2, 36, 1, 5],        clozeId: 36  },
  { id: 's106', sv: 'Vi ses snart.',            en: "See you soon.",                 wordIds: [10, 78],             clozeId: 78  },
  { id: 's107', sv: 'Det är dags att gå.',      en: "It's time to go.",              wordIds: [2, 3, 6, 73],        clozeId: 73  },
  { id: 's108', sv: 'Jag saknar dig.',          en: 'I miss you.',                   wordIds: [1, 21],              clozeId: 1   },
  { id: 's109', sv: 'Ta hand om dig.',          en: 'Take care of yourself.',        wordIds: [55, 21],             clozeId: 55  },
  { id: 's110', sv: 'Det var bra.',             en: 'That was good.',                wordIds: [2, 22, 51],          clozeId: 51  },
  { id: 's111', sv: 'Inte alls.',               en: 'Not at all.',                   wordIds: [5, 65],              clozeId: 65  },
  { id: 's112', sv: 'Visst!',                   en: 'Of course! / Sure!',            wordIds: [156],                clozeId: 156 },
  { id: 's113', sv: 'Det gör ont.',             en: 'It hurts.',                     wordIds: [2, 45],              clozeId: 45  },
  { id: 's114', sv: 'Jag måste tänka.',         en: 'I need to think.',              wordIds: [1, 46, 180],         clozeId: 180 },
  { id: 's115', sv: 'Hur gammal är du?',        en: 'How old are you?',              wordIds: [41, 4, 3],           clozeId: 41  },
  { id: 's116', sv: 'Var bor du?',              en: 'Where do you live?',            wordIds: [19, 4],              clozeId: 19  },
  { id: 's117', sv: 'Jag förstår dig.',         en: 'I understand you.',             wordIds: [1, 162, 21],         clozeId: 162 },
  { id: 's118', sv: 'Det är min tur.',          en: "It's my turn.",                 wordIds: [2, 3, 42],           clozeId: 42  },
  { id: 's119', sv: 'Vi är alla här.',          en: "We're all here.",               wordIds: [10, 3, 65, 19],      clozeId: 65  },
  { id: 's120', sv: 'Det spelar ingen roll.',   en: "It doesn't matter.",            wordIds: [2, 79],              clozeId: 79  },
];
