// Top 1,000 most common Swedish words
// Source: frequency list derived from opensubtitles.org corpus
// pos categories: verb, noun, adj, adv, pronoun, prep, conj, particle, numeral, name, interjection

const WORDS = [
  { id: 1, sv: 'jag', en: 'I', pos: 'pronoun' },
  { id: 2, sv: 'det', en: 'it / that', pos: 'pronoun' },
  { id: 3, sv: 'är', en: 'is / are', pos: 'verb' },
  { id: 4, sv: 'du', en: 'you', pos: 'pronoun' },
  { id: 5, sv: 'inte', en: 'not', pos: 'adv' },
  { id: 6, sv: 'att', en: 'to / that', pos: 'particle' },
  { id: 7, sv: 'en', en: 'a / an (common gender)', pos: 'particle' },
  { id: 8, sv: 'och', en: 'and', pos: 'conj' },
  { id: 9, sv: 'har', en: 'have / has', pos: 'verb' },
  { id: 10, sv: 'vi', en: 'we', pos: 'pronoun' },
  { id: 11, sv: 'på', en: 'on / at', pos: 'prep' },
  { id: 12, sv: 'i', en: 'in', pos: 'prep' },
  { id: 13, sv: 'för', en: 'for / because', pos: 'prep' },
  { id: 14, sv: 'han', en: 'he', pos: 'pronoun' },
  { id: 15, sv: 'vad', en: 'what', pos: 'pronoun' },
  { id: 16, sv: 'med', en: 'with', pos: 'prep' },
  { id: 17, sv: 'mig', en: 'me', pos: 'pronoun' },
  { id: 18, sv: 'som', en: 'who / which / as', pos: 'conj' },
  { id: 19, sv: 'här', en: 'here', pos: 'adv' },
  { id: 20, sv: 'om', en: 'if / about', pos: 'prep' },
  { id: 21, sv: 'dig', en: 'you (object)', pos: 'pronoun' },
  { id: 22, sv: 'var', en: 'was / were', pos: 'verb' },
  { id: 23, sv: 'den', en: 'it / the (common)', pos: 'pronoun' },
  { id: 24, sv: 'så', en: 'so / thus', pos: 'adv' },
  { id: 25, sv: 'till', en: 'to / until', pos: 'prep' },
  { id: 26, sv: 'kan', en: 'can / may', pos: 'verb' },
  { id: 27, sv: 'de', en: 'they', pos: 'pronoun' },
  { id: 28, sv: 'ni', en: 'you (plural)', pos: 'pronoun' },
  { id: 29, sv: 'ska', en: 'shall / will', pos: 'verb' },
  { id: 30, sv: 'ett', en: 'a / an (neuter)', pos: 'particle' },
  { id: 31, sv: 'men', en: 'but', pos: 'conj' },
  { id: 32, sv: 'av', en: 'of / by / from', pos: 'prep' },
  { id: 33, sv: 'vill', en: 'want / want to', pos: 'verb' },
  { id: 34, sv: 'nu', en: 'now', pos: 'adv' },
  { id: 35, sv: 'ja', en: 'yes', pos: 'interjection' },
  { id: 36, sv: 'vet', en: 'know', pos: 'verb' },
  { id: 37, sv: 'nej', en: 'no', pos: 'interjection' },
  { id: 38, sv: 'bara', en: 'only / just', pos: 'adv' },
  { id: 39, sv: 'hon', en: 'she', pos: 'pronoun' },
  { id: 40, sv: 'kommer', en: 'comes / will (future)', pos: 'verb' },
  { id: 41, sv: 'hur', en: 'how', pos: 'adv' },
  { id: 42, sv: 'min', en: 'my / mine', pos: 'pronoun' },
  { id: 43, sv: 'där', en: 'there / where', pos: 'adv' },
  { id: 44, sv: 'honom', en: 'him', pos: 'pronoun' },
  { id: 45, sv: 'gör', en: 'do / does / make', pos: 'verb' },
  { id: 46, sv: 'måste', en: 'must / have to', pos: 'verb' },
  { id: 47, sv: 'kom', en: 'came', pos: 'verb' },
  { id: 48, sv: 'din', en: 'your / yours', pos: 'pronoun' },
  { id: 49, sv: 'skulle', en: 'would / should', pos: 'verb' },
  { id: 50, sv: 'då', en: 'then / at that time', pos: 'adv' },
  { id: 51, sv: 'bra', en: 'good / well / fine', pos: 'adj' },
  { id: 52, sv: 'när', en: 'when', pos: 'conj' },
  { id: 53, sv: 'ha', en: 'have', pos: 'verb' },
  { id: 54, sv: 'er', en: 'you (plural object)', pos: 'pronoun' },
  { id: 55, sv: 'ta', en: 'take', pos: 'verb' },
  { id: 56, sv: 'ut', en: 'out', pos: 'adv' },
  { id: 57, sv: 'får', en: 'get / may / is allowed', pos: 'verb' },
  { id: 58, sv: 'man', en: 'one / you (impersonal) / man', pos: 'pronoun' },
  { id: 59, sv: 'vara', en: 'to be', pos: 'verb' },
  { id: 60, sv: 'oss', en: 'us', pos: 'pronoun' },
  { id: 61, sv: 'göra', en: 'to do / to make', pos: 'verb' },
  { id: 62, sv: 'dem', en: 'them', pos: 'pronoun' },
  { id: 63, sv: 'eller', en: 'or', pos: 'conj' },
  { id: 64, sv: 'varför', en: 'why', pos: 'adv' },
  { id: 65, sv: 'alla', en: 'all / everyone', pos: 'pronoun' },
  { id: 66, sv: 'från', en: 'from', pos: 'prep' },
  { id: 67, sv: 'upp', en: 'up', pos: 'adv' },
  { id: 68, sv: 'tror', en: 'believe / think', pos: 'verb' },
  { id: 69, sv: 'okej', en: 'okay', pos: 'interjection' },
  { id: 70, sv: 'igen', en: 'again', pos: 'adv' },
  { id: 71, sv: 'sa', en: 'said', pos: 'verb' },
  { id: 72, sv: 'tack', en: 'thank you / thanks', pos: 'interjection' },
  { id: 73, sv: 'gå', en: 'go / walk', pos: 'verb' },
  { id: 74, sv: 'hade', en: 'had', pos: 'verb' },
  { id: 75, sv: 'sig', en: 'oneself / himself / herself', pos: 'pronoun' },
  { id: 76, sv: 'in', en: 'in / into', pos: 'adv' },
  { id: 77, sv: 'allt', en: 'everything / all', pos: 'pronoun' },
  { id: 78, sv: 'se', en: 'see', pos: 'verb' },
  { id: 79, sv: 'ingen', en: 'nobody / none', pos: 'pronoun' },
  { id: 80, sv: 'få', en: 'get / few', pos: 'verb' },
  { id: 81, sv: 'henne', en: 'her', pos: 'pronoun' },
  { id: 82, sv: 'lite', en: 'a little / a bit', pos: 'adv' },
  { id: 83, sv: 'mycket', en: 'very / much / a lot', pos: 'adv' },
  { id: 84, sv: 'vem', en: 'who', pos: 'pronoun' },
  { id: 85, sv: 'går', en: 'goes / walks', pos: 'verb' },
  { id: 86, sv: 'ser', en: 'see / look', pos: 'verb' },
  { id: 87, sv: 'mitt', en: 'my / mine (neuter)', pos: 'pronoun' },
  { id: 88, sv: 'hej', en: 'hi / hello', pos: 'interjection' },
  { id: 89, sv: 'aldrig', en: 'never', pos: 'adv' },
  { id: 90, sv: 'kanske', en: 'maybe / perhaps', pos: 'adv' },
  { id: 91, sv: 'nåt', en: 'something (colloquial)', pos: 'pronoun' },
  { id: 92, sv: 'behöver', en: 'need / needs', pos: 'verb' },
  { id: 93, sv: 'finns', en: 'there is / there are / exists', pos: 'verb' },
  { id: 94, sv: 'blir', en: 'becomes / will be', pos: 'verb' },
  { id: 95, sv: 'än', en: 'than / yet', pos: 'conj' },
  { id: 96, sv: 'inget', en: 'nothing / no (neuter)', pos: 'pronoun' },
  { id: 97, sv: 'efter', en: 'after / behind', pos: 'prep' },
  { id: 98, sv: 'bli', en: 'become / be', pos: 'verb' },
  { id: 99, sv: 'ju', en: 'you know / of course (particle)', pos: 'particle' },
  { id: 100, sv: 'två', en: 'two', pos: 'numeral' },
  { id: 101, sv: 'något', en: 'something / somewhat', pos: 'pronoun' },
  { id: 102, sv: 'tar', en: 'takes', pos: 'verb' },
  { id: 103, sv: 'tillbaka', en: 'back', pos: 'adv' },
  { id: 104, sv: 'hans', en: 'his', pos: 'pronoun' },
  { id: 105, sv: 'över', en: 'over / above', pos: 'prep' },
  { id: 106, sv: 'sen', en: 'then / later / since', pos: 'adv' },
  { id: 107, sv: 'säger', en: 'say / says', pos: 'verb' },
  { id: 108, sv: 'ge', en: 'give', pos: 'verb' },
  { id: 109, sv: 'mer', en: 'more', pos: 'adv' },
  { id: 110, sv: 'ditt', en: 'your / yours (neuter)', pos: 'pronoun' },
  { id: 111, sv: 'gjorde', en: 'did / made', pos: 'verb' },
  { id: 112, sv: 'mina', en: 'my / mine (plural)', pos: 'pronoun' },
  { id: 113, sv: 'ner', en: 'down', pos: 'adv' },
  { id: 114, sv: 'åt', en: 'ate / for / towards', pos: 'verb' },
  { id: 115, sv: 'fan', en: 'damn / hell (mild expletive)', pos: 'interjection' },
  { id: 116, sv: 'någon', en: 'someone / anyone / some', pos: 'pronoun' },
  { id: 117, sv: 'väl', en: 'well / surely', pos: 'adv' },
  { id: 118, sv: 'nån', en: 'someone (colloquial)', pos: 'pronoun' },
  { id: 119, sv: 'vänta', en: 'wait', pos: 'verb' },
  { id: 120, sv: 'också', en: 'also / too', pos: 'adv' },
  { id: 121, sv: 'fick', en: 'got / received / was allowed', pos: 'verb' },
  { id: 122, sv: 'mr', en: 'Mr.', pos: 'noun' },
  { id: 123, sv: 'säga', en: 'to say', pos: 'verb' },
  { id: 124, sv: 'år', en: 'year', pos: 'noun' },
  { id: 125, sv: 'kunde', en: 'could', pos: 'verb' },
  { id: 126, sv: 'nog', en: 'enough / probably', pos: 'adv' },
  { id: 127, sv: 'låt', en: 'let / allow', pos: 'verb' },
  { id: 128, sv: 'varit', en: 'been', pos: 'verb' },
  { id: 129, sv: 'hit', en: 'here (to here)', pos: 'adv' },
  { id: 130, sv: 'pappa', en: 'dad / father', pos: 'noun' },
  { id: 131, sv: 'mamma', en: 'mum / mother', pos: 'noun' },
  { id: 132, sv: 'mot', en: 'against / towards', pos: 'prep' },
  { id: 133, sv: 'andra', en: 'other / second', pos: 'adj' },
  { id: 134, sv: 'hela', en: 'whole / entire', pos: 'adj' },
  { id: 135, sv: 'detta', en: 'this', pos: 'pronoun' },
  { id: 136, sv: 'känner', en: 'know / feel', pos: 'verb' },
  { id: 137, sv: 'vid', en: 'at / by / near', pos: 'prep' },
  { id: 138, sv: 'några', en: 'some / a few', pos: 'pronoun' },
  { id: 139, sv: 'komma', en: 'come', pos: 'verb' },
  { id: 140, sv: 'borde', en: 'should / ought to', pos: 'verb' },
  { id: 141, sv: 'rätt', en: 'right / correct', pos: 'adj' },
  { id: 142, sv: 'va', en: 'huh? / what? (colloquial)', pos: 'particle' },
  { id: 143, sv: 'menar', en: 'mean', pos: 'verb' },
  { id: 144, sv: 'själv', en: 'myself / yourself / oneself', pos: 'pronoun' },
  { id: 145, sv: 'alltid', en: 'always', pos: 'adv' },
  { id: 146, sv: 'hem', en: 'home', pos: 'noun' },
  { id: 147, sv: 'gjort', en: 'done / made', pos: 'verb' },
  { id: 148, sv: 'dina', en: 'your / yours (plural)', pos: 'pronoun' },
  { id: 149, sv: 'ville', en: 'wanted / wanted to', pos: 'verb' },
  { id: 150, sv: 'såg', en: 'saw', pos: 'verb' },
  { id: 151, sv: 'titta', en: 'look / watch', pos: 'verb' },
  { id: 152, sv: 'dag', en: 'day', pos: 'noun' },
  { id: 153, sv: 'verkligen', en: 'really / truly', pos: 'adv' },
  { id: 154, sv: 'fel', en: 'wrong / mistake / fault', pos: 'adj' },
  { id: 155, sv: 'utan', en: 'without', pos: 'prep' },
  { id: 156, sv: 'visst', en: 'of course / certainly', pos: 'adv' },
  { id: 157, sv: 'tre', en: 'three', pos: 'numeral' },
  { id: 158, sv: 'prata', en: 'talk / speak', pos: 'verb' },
  { id: 159, sv: 'vår', en: 'our / spring', pos: 'pronoun' },
  { id: 160, sv: 'liv', en: 'life', pos: 'noun' },
  { id: 161, sv: 'sätt', en: 'way / manner', pos: 'noun' },
  { id: 162, sv: 'förstår', en: 'understand / understands', pos: 'verb' },
  { id: 163, sv: 'älskar', en: 'love / loves', pos: 'verb' },
  { id: 164, sv: 'blev', en: 'became / got', pos: 'verb' },
  { id: 165, sv: 'tog', en: 'took', pos: 'verb' },
  { id: 166, sv: 'håll', en: 'hold', pos: 'verb' },
  { id: 167, sv: 'dom', en: 'them / they (colloquial)', pos: 'pronoun' },
  { id: 168, sv: 'döda', en: 'kill / dead', pos: 'verb' },
  { id: 169, sv: 'tid', en: 'time', pos: 'noun' },
  { id: 170, sv: 'tycker', en: 'think / feel / like', pos: 'verb' },
  { id: 171, sv: 'sluta', en: 'stop / quit / end', pos: 'verb' },
  { id: 172, sv: 'trodde', en: 'thought / believed', pos: 'verb' },
  { id: 173, sv: 'gillar', en: 'like / likes', pos: 'verb' },
  { id: 174, sv: 'precis', en: 'exactly / just', pos: 'adv' },
  { id: 175, sv: 'säg', en: 'say (imperative)', pos: 'verb' },
  { id: 176, sv: 'bort', en: 'away', pos: 'adv' },
  { id: 177, sv: 'sin', en: 'his / her / its (reflexive)', pos: 'pronoun' },
  { id: 178, sv: 'gång', en: 'time / occasion / walk', pos: 'noun' },
  { id: 179, sv: 'inga', en: 'no / none (plural)', pos: 'pronoun' },
  { id: 180, sv: 'tänker', en: 'think / intend', pos: 'verb' },
  { id: 181, sv: 'hör', en: 'hear / listen', pos: 'verb' },
  { id: 182, sv: 'veta', en: 'know / to know', pos: 'verb' },
  { id: 183, sv: 'gud', en: 'god', pos: 'noun' },
  { id: 184, sv: 'bättre', en: 'better', pos: 'adj' },
  { id: 185, sv: 'just', en: 'just / right now', pos: 'adv' },
  { id: 186, sv: 'berätta', en: 'tell / explain', pos: 'verb' },
  { id: 187, sv: 'många', en: 'many / much', pos: 'adj' },
  { id: 188, sv: 'barn', en: 'child / children', pos: 'noun' },
  { id: 189, sv: 'gick', en: 'went / walked', pos: 'verb' },
  { id: 190, sv: 'god', en: 'good / kind', pos: 'adj' },
  { id: 191, sv: 'hjälp', en: 'help', pos: 'noun' },
  { id: 192, sv: 'händer', en: 'happens / hands', pos: 'verb' },
  { id: 193, sv: 'under', en: 'under / during', pos: 'prep' },
  { id: 194, sv: 'sett', en: 'seen', pos: 'verb' },
  { id: 195, sv: 'visste', en: 'knew', pos: 'verb' },
  { id: 196, sv: 'innan', en: 'before', pos: 'conj' },
  { id: 197, sv: 'förlåt', en: 'sorry / forgive', pos: 'interjection' },
  { id: 198, sv: 'helt', en: 'completely / quite', pos: 'adv' },
  { id: 199, sv: 'folk', en: 'people / folk', pos: 'noun' },
  { id: 200, sv: 'pengar', en: 'money', pos: 'noun' },
  { id: 201, sv: 'död', en: 'dead / death', pos: 'adj' },
  { id: 202, sv: 'första', en: 'first', pos: 'numeral' },
  { id: 203, sv: 'hjälpa', en: 'help / to help', pos: 'verb' },
  { id: 204, sv: 'ursäkta', en: 'excuse me', pos: 'interjection' },
  { id: 205, sv: 'snälla', en: 'please', pos: 'particle' },
  { id: 206, sv: 'länge', en: 'for a long time / long', pos: 'adv' },
  { id: 207, sv: 'heter', en: 'is called / am called', pos: 'verb' },
  { id: 208, sv: 'ledsen', en: 'sorry / sad', pos: 'adj' },
  { id: 209, sv: 'stanna', en: 'stay / stop', pos: 'verb' },
  { id: 210, sv: 'vart', en: 'where (to)', pos: 'adv' },
  { id: 211, sv: 'helvete', en: 'hell', pos: 'noun' },
  { id: 212, sv: 'vilken', en: 'which / what (common)', pos: 'pronoun' },
  { id: 213, sv: 'hennes', en: 'her / hers', pos: 'pronoun' },
  { id: 214, sv: 'står', en: 'stand / stands', pos: 'verb' },
  { id: 215, sv: 'saker', en: 'things', pos: 'noun' },
  { id: 216, sv: 'far', en: 'father', pos: 'noun' },
  { id: 217, sv: 'borta', en: 'away / gone', pos: 'adv' },
  { id: 218, sv: 'hallå', en: 'hello', pos: 'interjection' },
  { id: 219, sv: 'håller', en: 'hold / keep / agree', pos: 'verb' },
  { id: 220, sv: 'fortfarande', en: 'still', pos: 'adv' },
  { id: 221, sv: 'kör', en: 'drive / run', pos: 'verb' },
  { id: 222, sv: 'ur', en: 'out of', pos: 'prep' },
  { id: 223, sv: 'hand', en: 'hand', pos: 'noun' },
  { id: 224, sv: 'problem', en: 'problem', pos: 'noun' },
  { id: 225, sv: 'ger', en: 'give / gives', pos: 'verb' },
  { id: 226, sv: 'sak', en: 'thing', pos: 'noun' },
  { id: 227, sv: 'morgon', en: 'morning / tomorrow', pos: 'noun' },
  { id: 228, sv: 'ens', en: 'even / one\'s', pos: 'adv' },
  { id: 229, sv: 'åh', en: 'oh', pos: 'interjection' },
  { id: 230, sv: 'väg', en: 'road / way / path', pos: 'noun' },
  { id: 231, sv: 'vän', en: 'friend', pos: 'noun' },
  { id: 232, sv: 'våra', en: 'our / ours (plural)', pos: 'pronoun' },
  { id: 233, sv: 'mår', en: 'feel (health)', pos: 'verb' },
  { id: 234, sv: 'enda', en: 'only / sole', pos: 'adj' },
  { id: 235, sv: 'hitta', en: 'find', pos: 'verb' },
  { id: 236, sv: 'kvar', en: 'left / remaining', pos: 'adv' },
  { id: 237, sv: 'samma', en: 'same', pos: 'adj' },
  { id: 238, sv: 'kväll', en: 'evening', pos: 'noun' },
  { id: 239, sv: 'försöker', en: 'try / tries', pos: 'verb' },
  { id: 240, sv: 'ute', en: 'outside / out', pos: 'adv' },
  { id: 241, sv: 'namn', en: 'name', pos: 'noun' },
  { id: 242, sv: 'dit', en: 'there (to there)', pos: 'adv' },
  { id: 243, sv: 'ingenting', en: 'nothing', pos: 'pronoun' },
  { id: 244, sv: 'snart', en: 'soon', pos: 'adv' },
  { id: 245, sv: 'fått', en: 'gotten / received', pos: 'verb' },
  { id: 246, sv: 'annan', en: 'other / another', pos: 'adj' },
  { id: 247, sv: 'väldigt', en: 'very / extremely', pos: 'adv' },
  { id: 248, sv: 'fru', en: 'wife / Mrs.', pos: 'noun' },
  { id: 249, sv: 'längre', en: 'longer / any more', pos: 'adv' },
  { id: 250, sv: 'sitt', en: 'his / her / its (reflexive, neuter)', pos: 'pronoun' },
  { id: 251, sv: 'hände', en: 'happened', pos: 'verb' },
  { id: 252, sv: 'redan', en: 'already', pos: 'adv' },
  { id: 253, sv: 'bästa', en: 'best', pos: 'adj' },
  { id: 254, sv: 'pratar', en: 'talk / speak', pos: 'verb' },
  { id: 255, sv: 'visa', en: 'show', pos: 'verb' },
  { id: 256, sv: 'kolla', en: 'check / look', pos: 'verb' },
  { id: 257, sv: 'tiden', en: 'the time', pos: 'noun' },
  { id: 258, sv: 'slut', en: 'end / over', pos: 'noun' },
  { id: 259, sv: 'sedan', en: 'then / since / afterwards', pos: 'adv' },
  { id: 260, sv: 'låter', en: 'sound / let / allow', pos: 'verb' },
  { id: 261, sv: 'tro', en: 'believe / faith', pos: 'verb' },
  { id: 262, sv: 'fram', en: 'forward / ahead', pos: 'adv' },
  { id: 263, sv: 'fråga', en: 'question / ask', pos: 'noun' },
  { id: 264, sv: 'stor', en: 'big / large', pos: 'adj' },
  { id: 265, sv: 'träffa', en: 'meet / hit', pos: 'verb' },
  { id: 266, sv: 'varje', en: 'every / each', pos: 'adj' },
  { id: 267, sv: 'först', en: 'first / at first', pos: 'adv' },
  { id: 268, sv: 'säkert', en: 'certainly / safely', pos: 'adv' },
  { id: 269, sv: 'deras', en: 'their / theirs', pos: 'pronoun' },
  { id: 270, sv: 'börjar', en: 'begin / start', pos: 'verb' },
  { id: 271, sv: 'åka', en: 'go / travel', pos: 'verb' },
  { id: 272, sv: 'rädd', en: 'afraid / scared', pos: 'adj' },
  { id: 273, sv: 'därför', en: 'therefore / that\'s why', pos: 'adv' },
  { id: 274, sv: 'jobb', en: 'job / work', pos: 'noun' },
  { id: 275, sv: 'lämna', en: 'leave / hand over', pos: 'verb' },
  { id: 276, sv: 'hos', en: 'at / with (someone\'s place)', pos: 'prep' },
  { id: 277, sv: 'fem', en: 'five', pos: 'numeral' },
  { id: 278, sv: 'tänkte', en: 'thought / was thinking', pos: 'verb' },
  { id: 279, sv: 'säker', en: 'sure / safe / certain', pos: 'adj' },
  { id: 280, sv: 'hoppas', en: 'hope', pos: 'verb' },
  { id: 281, sv: 'liten', en: 'small / little', pos: 'adj' },
  { id: 282, sv: 'genom', en: 'through / by', pos: 'prep' },
  { id: 283, sv: 'kunna', en: 'to be able to / can', pos: 'verb' },
  { id: 284, sv: 'hörde', en: 'heard', pos: 'verb' },
  { id: 285, sv: 'nästa', en: 'next', pos: 'adj' },
  { id: 286, sv: 'sex', en: 'six', pos: 'numeral' },
  { id: 287, sv: 'livet', en: 'the life', pos: 'noun' },
  { id: 288, sv: 'lyssna', en: 'listen', pos: 'verb' },
  { id: 289, sv: 'son', en: 'son', pos: 'noun' },
  { id: 290, sv: 'verkar', en: 'seem / seems', pos: 'verb' },
  { id: 291, sv: 'sista', en: 'last / final', pos: 'adj' },
  { id: 292, sv: 'vänner', en: 'friends', pos: 'noun' },
  { id: 293, sv: 'hålla', en: 'hold / keep', pos: 'verb' },
  { id: 294, sv: 'riktigt', en: 'really / properly', pos: 'adv' },
  { id: 295, sv: 'tala', en: 'speak / talk', pos: 'verb' },
  { id: 296, sv: 'dö', en: 'die', pos: 'verb' },
  { id: 297, sv: 'sant', en: 'true', pos: 'adj' },
  { id: 298, sv: 'klarar', en: 'manage / handle', pos: 'verb' },
  { id: 299, sv: 'sina', en: 'his / her / their (reflexive, plural)', pos: 'pronoun' },
  { id: 300, sv: 'ihop', en: 'together', pos: 'adv' },
  { id: 301, sv: 'gav', en: 'gave', pos: 'verb' },
  { id: 302, sv: 'dra', en: 'pull / draw / go', pos: 'verb' },
  { id: 303, sv: 'nya', en: 'new (plural)', pos: 'adj' },
  { id: 304, sv: 'väntar', en: 'wait / waits', pos: 'verb' },
  { id: 305, sv: 'vilket', en: 'which (neuter)', pos: 'pronoun' },
  { id: 306, sv: 'minuter', en: 'minutes', pos: 'noun' },
  { id: 307, sv: 'höra', en: 'hear', pos: 'verb' },
  { id: 308, sv: 'världen', en: 'the world', pos: 'noun' },
  { id: 309, sv: 'tills', en: 'until', pos: 'conj' },
  { id: 310, sv: 'älskling', en: 'darling / sweetheart', pos: 'noun' },
  { id: 311, sv: 'fyra', en: 'four', pos: 'numeral' },
  { id: 312, sv: 'fast', en: 'although / but / stuck', pos: 'conj' },
  { id: 313, sv: 'människor', en: 'people / humans', pos: 'noun' },
  { id: 314, sv: 'hemma', en: 'at home', pos: 'adv' },
  { id: 315, sv: 'klart', en: 'clear / of course / done', pos: 'adv' },
  { id: 316, sv: 'blivit', en: 'become / been', pos: 'verb' },
  { id: 317, sv: 'idag', en: 'today', pos: 'adv' },
  { id: 318, sv: 'minns', en: 'remember', pos: 'verb' },
  { id: 319, sv: 'hämta', en: 'fetch / pick up', pos: 'verb' },
  { id: 320, sv: 'lugnt', en: 'calmly / take it easy', pos: 'adv' },
  { id: 321, sv: 'runt', en: 'around', pos: 'prep' },
  { id: 322, sv: 'del', en: 'part / portion', pos: 'noun' },
  { id: 323, sv: 'sagt', en: 'said', pos: 'verb' },
  { id: 324, sv: 'vårt', en: 'our / ours (neuter)', pos: 'pronoun' },
  { id: 325, sv: 'stora', en: 'big / large (plural)', pos: 'adj' },
  { id: 326, sv: 'annars', en: 'otherwise / or else', pos: 'adv' },
  { id: 327, sv: 'inne', en: 'inside', pos: 'adv' },
  { id: 328, sv: 'lilla', en: 'little / small (definite)', pos: 'adj' },
  { id: 329, sv: 'öppna', en: 'open', pos: 'verb' },
  { id: 330, sv: 'polisen', en: 'the police', pos: 'noun' },
  { id: 331, sv: 'tur', en: 'luck / turn', pos: 'noun' },
  { id: 332, sv: 'även', en: 'also / even', pos: 'adv' },
  { id: 333, sv: 'spelar', en: 'play / plays / act', pos: 'verb' },
  { id: 334, sv: 'lika', en: 'equally / as', pos: 'adv' },
  { id: 335, sv: 'haft', en: 'had', pos: 'verb' },
  { id: 336, sv: 'illa', en: 'badly / ill', pos: 'adv' },
  { id: 337, sv: 'hittade', en: 'found', pos: 'verb' },
  { id: 338, sv: 'kvinna', en: 'woman', pos: 'noun' },
  { id: 339, sv: 'ensam', en: 'alone', pos: 'adj' },
  { id: 340, sv: 'hört', en: 'heard', pos: 'verb' },
  { id: 341, sv: 'ändå', en: 'anyway / still / nevertheless', pos: 'adv' },
  { id: 342, sv: 'bil', en: 'car', pos: 'noun' },
  { id: 343, sv: 'faktiskt', en: 'actually / in fact', pos: 'adv' },
  { id: 344, sv: 'nästan', en: 'almost / nearly', pos: 'adv' },
  { id: 345, sv: 'ny', en: 'new', pos: 'adj' },
  { id: 346, sv: 'kul', en: 'fun / funny', pos: 'adj' },
  { id: 347, sv: 'natt', en: 'night', pos: 'noun' },
  { id: 348, sv: 'spela', en: 'play', pos: 'verb' },
  { id: 349, sv: 'dog', en: 'died', pos: 'verb' },
  { id: 350, sv: 'långt', en: 'far / long way', pos: 'adv' },
  { id: 351, sv: 'börja', en: 'start / begin', pos: 'verb' },
  { id: 352, sv: 'senare', en: 'later', pos: 'adv' },
  { id: 353, sv: 'killen', en: 'the guy / the boy', pos: 'noun' },
  { id: 354, sv: 'bäst', en: 'best', pos: 'adj' },
  { id: 355, sv: 'heller', en: 'either / nor', pos: 'adv' },
  { id: 356, sv: 'gott', en: 'good / tasty', pos: 'adj' },
  { id: 357, sv: 'huset', en: 'the house', pos: 'noun' },
  { id: 358, sv: 'kille', en: 'guy / boy', pos: 'noun' },
  { id: 359, sv: 'tillsammans', en: 'together', pos: 'adv' },
  { id: 360, sv: 'trevligt', en: 'nice / pleasant', pos: 'adj' },
  { id: 361, sv: 'plats', en: 'place / seat', pos: 'noun' },
  { id: 362, sv: 'hus', en: 'house', pos: 'noun' },
  { id: 363, sv: 'ringer', en: 'call / ring', pos: 'verb' },
  { id: 364, sv: 'hittar', en: 'find / finds', pos: 'verb' },
  { id: 365, sv: 'familj', en: 'family', pos: 'noun' },
  { id: 366, sv: 'bor', en: 'live / reside', pos: 'verb' },
  { id: 367, sv: 'sitter', en: 'sit / sits', pos: 'verb' },
  { id: 368, sv: 'tio', en: 'ten', pos: 'numeral' },
  { id: 369, sv: 'vilka', en: 'which / who (plural)', pos: 'pronoun' },
  { id: 370, sv: 'redo', en: 'ready', pos: 'adj' },
  { id: 371, sv: 'jobbar', en: 'work / works', pos: 'verb' },
  { id: 372, sv: 'gammal', en: 'old', pos: 'adj' },
  { id: 373, sv: 'äta', en: 'eat', pos: 'verb' },
  { id: 374, sv: 'dörren', en: 'the door', pos: 'noun' },
  { id: 375, sv: 'glad', en: 'happy / glad', pos: 'adj' },
  { id: 376, sv: 'tyst', en: 'quiet / silent', pos: 'adj' },
  { id: 377, sv: 'chans', en: 'chance', pos: 'noun' },
  { id: 378, sv: 'försökte', en: 'tried', pos: 'verb' },
  { id: 379, sv: 'rum', en: 'room', pos: 'noun' },
  { id: 380, sv: 'känns', en: 'feels / seems', pos: 'verb' },
  { id: 381, sv: 'båda', en: 'both', pos: 'adj' },
  { id: 382, sv: 'gamla', en: 'old (plural)', pos: 'adj' },
  { id: 383, sv: 'nära', en: 'near / close', pos: 'adj' },
  { id: 384, sv: 'klockan', en: 'the clock / o\'clock', pos: 'noun' },
  { id: 385, sv: 'svårt', en: 'difficult / hard', pos: 'adj' },
  { id: 386, sv: 'gått', en: 'gone / walked', pos: 'verb' },
  { id: 387, sv: 'par', en: 'couple / pair', pos: 'noun' },
  { id: 388, sv: 'dessa', en: 'these', pos: 'pronoun' },
  { id: 389, sv: 'mannen', en: 'the man', pos: 'noun' },
  { id: 390, sv: 'dagar', en: 'days', pos: 'noun' },
  { id: 391, sv: 'ord', en: 'word', pos: 'noun' },
  { id: 392, sv: 'ibland', en: 'sometimes', pos: 'adv' },
  { id: 393, sv: 'fint', en: 'fine / nice / pretty', pos: 'adj' },
  { id: 394, sv: 'bror', en: 'brother', pos: 'noun' },
  { id: 395, sv: 'gånger', en: 'times (occasions)', pos: 'noun' },
  { id: 396, sv: 'ännu', en: 'yet / still / even', pos: 'adv' },
  { id: 397, sv: 'galen', en: 'crazy / mad', pos: 'adj' },
  { id: 398, sv: 'rädda', en: 'save / rescue', pos: 'verb' },
  { id: 399, sv: 'dör', en: 'die / dies', pos: 'verb' },
  { id: 400, sv: 'mor', en: 'mother', pos: 'noun' },
  { id: 401, sv: 'bakom', en: 'behind', pos: 'prep' },
  { id: 402, sv: 'mellan', en: 'between', pos: 'prep' },
  { id: 403, sv: 'ringa', en: 'call / ring', pos: 'verb' },
  { id: 404, sv: 'timmar', en: 'hours', pos: 'noun' },
  { id: 405, sv: 'fler', en: 'more (quantity)', pos: 'adj' },
  { id: 406, sv: 'skynda', en: 'hurry', pos: 'verb' },
  { id: 407, sv: 'killar', en: 'guys / boys', pos: 'noun' },
  { id: 408, sv: 'mat', en: 'food', pos: 'noun' },
  { id: 409, sv: 'stannar', en: 'stop / stay', pos: 'verb' },
  { id: 410, sv: 'stå', en: 'stand', pos: 'verb' },
  { id: 411, sv: 'försök', en: 'try / attempt', pos: 'noun' },
  { id: 412, sv: 'känna', en: 'feel / know (a person)', pos: 'verb' },
  { id: 413, sv: 'leva', en: 'live', pos: 'verb' },
  { id: 414, sv: 'jobbet', en: 'the job', pos: 'noun' },
  { id: 415, sv: 'dotter', en: 'daughter', pos: 'noun' },
  { id: 416, sv: 'kände', en: 'felt / knew', pos: 'verb' },
  { id: 417, sv: 'ben', en: 'leg / bone', pos: 'noun' },
  { id: 418, sv: 'började', en: 'began / started', pos: 'verb' },
  { id: 419, sv: 'varandra', en: 'each other / one another', pos: 'pronoun' },
  { id: 420, sv: 'igenom', en: 'through', pos: 'prep' },
  { id: 421, sv: 'flicka', en: 'girl', pos: 'noun' },
  { id: 422, sv: 'ring', en: 'ring / call', pos: 'noun' },
  { id: 423, sv: 'räcker', en: 'enough / suffice', pos: 'verb' },
  { id: 424, sv: 'stället', en: 'the place / instead', pos: 'noun' },
  { id: 425, sv: 'syster', en: 'sister', pos: 'noun' },
  { id: 426, sv: 'dagen', en: 'the day', pos: 'noun' },
  { id: 427, sv: 'skolan', en: 'the school', pos: 'noun' },
  { id: 428, sv: 'lätt', en: 'easy / light', pos: 'adj' },
  { id: 429, sv: 'fin', en: 'fine / pretty / nice', pos: 'adj' },
  { id: 430, sv: 'fanns', en: 'was / existed', pos: 'verb' },
  { id: 431, sv: 'nere', en: 'down / below', pos: 'adv' },
  { id: 432, sv: 'ikväll', en: 'tonight', pos: 'adv' },
  { id: 433, sv: 'sätta', en: 'put / set / place', pos: 'verb' },
  { id: 434, sv: 'idé', en: 'idea', pos: 'noun' },
  { id: 435, sv: 'vatten', en: 'water', pos: 'noun' },
  { id: 436, sv: 'följa', en: 'follow', pos: 'verb' },
  { id: 437, sv: 'roligt', en: 'fun / funny', pos: 'adj' },
  { id: 438, sv: 'följer', en: 'follow / follows', pos: 'verb' },
  { id: 439, sv: 'ganska', en: 'quite / rather / fairly', pos: 'adv' },
  { id: 440, sv: 'vacker', en: 'beautiful', pos: 'adj' },
  { id: 441, sv: 'lovar', en: 'promise', pos: 'verb' },
  { id: 442, sv: 'flytta', en: 'move', pos: 'verb' },
  { id: 443, sv: 'bad', en: 'bath / asked', pos: 'noun' },
  { id: 444, sv: 'fara', en: 'danger / go', pos: 'noun' },
  { id: 445, sv: 'försöka', en: 'try / to try', pos: 'verb' },
  { id: 446, sv: 'tagit', en: 'taken', pos: 'verb' },
  { id: 447, sv: 'något', en: 'something / anything', pos: 'pronoun' },
  { id: 448, sv: 'eftersom', en: 'because / since', pos: 'conj' },
  { id: 449, sv: 'hatar', en: 'hate / hates', pos: 'verb' },
  { id: 450, sv: 'lång', en: 'long / tall', pos: 'adj' },
  { id: 451, sv: 'stort', en: 'big / large (neuter)', pos: 'adj' },
  { id: 452, sv: 'lära', en: 'learn / teach', pos: 'verb' },
  { id: 453, sv: 'köra', en: 'drive', pos: 'verb' },
  { id: 454, sv: 'förut', en: 'before / previously', pos: 'adv' },
  { id: 455, sv: 'hjälper', en: 'help / helps', pos: 'verb' },
  { id: 456, sv: 'antar', en: 'assume / suppose', pos: 'verb' },
  { id: 457, sv: 'lugn', en: 'calm', pos: 'adj' },
  { id: 458, sv: 'perfekt', en: 'perfect', pos: 'adj' },
  { id: 459, sv: 'skicka', en: 'send', pos: 'verb' },
  { id: 460, sv: 'utanför', en: 'outside', pos: 'prep' },
  { id: 461, sv: 'letar', en: 'look for / search', pos: 'verb' },
  { id: 462, sv: 'ont', en: 'pain / ache', pos: 'noun' },
  { id: 463, sv: 'kompis', en: 'friend / buddy', pos: 'noun' },
  { id: 464, sv: 'stoppa', en: 'stop', pos: 'verb' },
  { id: 465, sv: 'plan', en: 'plan', pos: 'noun' },
  { id: 466, sv: 'betala', en: 'pay', pos: 'verb' },
  { id: 467, sv: 'imorgon', en: 'tomorrow', pos: 'adv' },
  { id: 468, sv: 'önskar', en: 'wish / hope', pos: 'verb' },
  { id: 469, sv: 'nummer', en: 'number', pos: 'noun' },
  { id: 470, sv: 'snäll', en: 'kind / nice', pos: 'adj' },
  { id: 471, sv: 'nytt', en: 'new (neuter)', pos: 'adj' },
  { id: 472, sv: 'huvud', en: 'head', pos: 'noun' },
  { id: 473, sv: 'självklart', en: 'of course / obviously', pos: 'adv' },
  { id: 474, sv: 'mest', en: 'most', pos: 'adv' },
  { id: 475, sv: 'natten', en: 'the night', pos: 'noun' },
  { id: 476, sv: 'kärlek', en: 'love', pos: 'noun' },
  { id: 477, sv: 'sent', en: 'late', pos: 'adv' },
  { id: 478, sv: 'månader', en: 'months', pos: 'noun' },
  { id: 479, sv: 'jobba', en: 'work', pos: 'verb' },
  { id: 480, sv: 'hoppa', en: 'jump', pos: 'verb' },
  { id: 481, sv: 'snabbt', en: 'quickly / fast', pos: 'adv' },
  { id: 482, sv: 'pojke', en: 'boy', pos: 'noun' },
  { id: 483, sv: 'skriva', en: 'write', pos: 'verb' },
  { id: 484, sv: 'direkt', en: 'directly / straight', pos: 'adv' },
  { id: 485, sv: 'köpa', en: 'buy', pos: 'verb' },
  { id: 486, sv: 'före', en: 'before / in front of', pos: 'prep' },
  { id: 487, sv: 'tittar', en: 'look / watch', pos: 'verb' },
  { id: 488, sv: 'sova', en: 'sleep', pos: 'verb' },
  { id: 489, sv: 'kort', en: 'short / card', pos: 'adj' },
  { id: 490, sv: 'äter', en: 'eat / eats', pos: 'verb' },
  { id: 491, sv: 'tjej', en: 'girl', pos: 'noun' },
  { id: 492, sv: 'vecka', en: 'week', pos: 'noun' },
  { id: 493, sv: 'viktigt', en: 'important', pos: 'adj' },
  { id: 494, sv: 'ögon', en: 'eyes', pos: 'noun' },
  { id: 495, sv: 'föräldrar', en: 'parents', pos: 'noun' },
  { id: 496, sv: 'välkommen', en: 'welcome', pos: 'adj' },
  { id: 497, sv: 'lämnade', en: 'left / left behind', pos: 'verb' },
  { id: 498, sv: 'skjuta', en: 'shoot', pos: 'verb' },
  { id: 499, sv: 'resten', en: 'the rest', pos: 'noun' },
  { id: 500, sv: 'hjärta', en: 'heart', pos: 'noun' },
  { id: 501, sv: 'lycka', en: 'happiness / luck', pos: 'noun' },
  { id: 502, sv: 'lämnar', en: 'leave / leaves', pos: 'verb' },
  { id: 503, sv: 'sitta', en: 'sit', pos: 'verb' },
  { id: 504, sv: 'veckor', en: 'weeks', pos: 'noun' },
  { id: 505, sv: 'satt', en: 'sat', pos: 'verb' },
  { id: 506, sv: 'sju', en: 'seven', pos: 'numeral' },
  { id: 507, sv: 'hårt', en: 'hard / firmly', pos: 'adv' },
  { id: 508, sv: 'använda', en: 'use', pos: 'verb' },
  { id: 509, sv: 'undrar', en: 'wonder / wonder about', pos: 'verb' },
  { id: 510, sv: 'sida', en: 'side / page', pos: 'noun' },
  { id: 511, sv: 'flera', en: 'several / more', pos: 'adj' },
  { id: 512, sv: 'svara', en: 'answer / reply', pos: 'verb' },
  { id: 513, sv: 'trött', en: 'tired', pos: 'adj' },
  { id: 514, sv: 'medan', en: 'while', pos: 'conj' },
  { id: 515, sv: 'allihop', en: 'everyone / all of them', pos: 'pronoun' },
  { id: 516, sv: 'blod', en: 'blood', pos: 'noun' },
  { id: 517, sv: 'alltså', en: 'so / thus / that is', pos: 'adv' },
  { id: 518, sv: 'förstå', en: 'understand', pos: 'verb' },
  { id: 519, sv: 'pratade', en: 'talked / spoke', pos: 'verb' },
  { id: 520, sv: 'älskade', en: 'loved', pos: 'verb' },
  { id: 521, sv: 'val', en: 'choice / election / whale', pos: 'noun' },
  { id: 522, sv: 'kära', en: 'dear / beloved', pos: 'adj' },
  { id: 523, sv: 'inom', en: 'within / inside', pos: 'prep' },
  { id: 524, sv: 'vissa', en: 'certain / some', pos: 'adj' },
  { id: 525, sv: 'miljoner', en: 'millions', pos: 'numeral' },
  { id: 526, sv: 'barnen', en: 'the children', pos: 'noun' },
  { id: 527, sv: 'tyvärr', en: 'unfortunately', pos: 'adv' },
  { id: 528, sv: 'land', en: 'country / land', pos: 'noun' },
  { id: 529, sv: 'igår', en: 'yesterday', pos: 'adv' },
  { id: 530, sv: 'tidigare', en: 'earlier / previously / former', pos: 'adv' },
  { id: 531, sv: 'skyldig', en: 'guilty / obligated', pos: 'adj' },
  { id: 532, sv: 'arg', en: 'angry', pos: 'adj' },
  { id: 533, sv: 'konstigt', en: 'strange / odd', pos: 'adj' },
  { id: 534, sv: 'kaffe', en: 'coffee', pos: 'noun' },
  { id: 535, sv: 'förklara', en: 'explain', pos: 'verb' },
  { id: 536, sv: 'otroligt', en: 'incredible / incredibly', pos: 'adv' },
  { id: 537, sv: 'tillräckligt', en: 'enough / sufficient', pos: 'adv' },
  { id: 538, sv: 'mindre', en: 'less / smaller', pos: 'adv' },
  { id: 539, sv: 'synd', en: 'pity / sin', pos: 'noun' },
  { id: 540, sv: 'åtta', en: 'eight', pos: 'numeral' },
  { id: 541, sv: 'hälsa', en: 'health / greet', pos: 'noun' },
  { id: 542, sv: 'riktig', en: 'real / proper', pos: 'adj' },
  { id: 543, sv: 'misstag', en: 'mistake', pos: 'noun' },
  { id: 544, sv: 'ögonblick', en: 'moment / instant', pos: 'noun' },
  { id: 545, sv: 'läsa', en: 'read', pos: 'verb' },
  { id: 546, sv: 'sjuk', en: 'sick / ill', pos: 'adj' },
  { id: 547, sv: 'polis', en: 'police / officer', pos: 'noun' },
  { id: 548, sv: 'frågor', en: 'questions', pos: 'noun' },
  { id: 549, sv: 'historia', en: 'history / story', pos: 'noun' },
  { id: 550, sv: 'middag', en: 'dinner / noon', pos: 'noun' },
  { id: 551, sv: 'absolut', en: 'absolutely', pos: 'adv' },
  { id: 552, sv: 'stund', en: 'moment / while', pos: 'noun' },
  { id: 553, sv: 'bo', en: 'live / reside', pos: 'verb' },
  { id: 554, sv: 'behövde', en: 'needed', pos: 'verb' },
  { id: 555, sv: 'förbi', en: 'past / by', pos: 'prep' },
  { id: 556, sv: 'krig', en: 'war', pos: 'noun' },
  { id: 557, sv: 'möjligt', en: 'possible', pos: 'adj' },
  { id: 558, sv: 'framför', en: 'in front of', pos: 'prep' },
  { id: 559, sv: 'flickan', en: 'the girl', pos: 'noun' },
  { id: 560, sv: 'fortsätta', en: 'continue', pos: 'verb' },
  { id: 561, sv: 'skjuter', en: 'shoot / shoots', pos: 'verb' },
  { id: 562, sv: 'slutar', en: 'end / stop / quit', pos: 'verb' },
  { id: 563, sv: 'jorden', en: 'the earth / the ground', pos: 'noun' },
  { id: 564, sv: 'resa', en: 'travel / trip', pos: 'noun' },
  { id: 565, sv: 'ung', en: 'young', pos: 'adj' },
  { id: 566, sv: 'hemskt', en: 'terrible / horribly', pos: 'adj' },
  { id: 567, sv: 'fungerar', en: 'work / function', pos: 'verb' },
  { id: 568, sv: 'enkelt', en: 'simply / easily', pos: 'adv' },
  { id: 569, sv: 'frågar', en: 'ask / asks', pos: 'verb' },
  { id: 570, sv: 'exakt', en: 'exactly', pos: 'adv' },
  { id: 571, sv: 'dåligt', en: 'badly / poorly', pos: 'adv' },
  { id: 572, sv: 'berättar', en: 'tell / tells', pos: 'verb' },
  { id: 573, sv: 'hund', en: 'dog', pos: 'noun' },
  { id: 574, sv: 'ansikte', en: 'face', pos: 'noun' },
  { id: 575, sv: 'arbete', en: 'work / job', pos: 'noun' },
  { id: 576, sv: 'träffade', en: 'met', pos: 'verb' },
  { id: 577, sv: 'huvud', en: 'head', pos: 'noun' },
  { id: 578, sv: 'landet', en: 'the country', pos: 'noun' },
  { id: 579, sv: 'allting', en: 'everything', pos: 'pronoun' },
  { id: 580, sv: 'trevlig', en: 'nice / pleasant', pos: 'adj' },
  { id: 581, sv: 'använder', en: 'use / uses', pos: 'verb' },
  { id: 582, sv: 'överallt', en: 'everywhere', pos: 'adv' },
  { id: 583, sv: 'jobbat', en: 'worked', pos: 'verb' },
  { id: 584, sv: 'värre', en: 'worse', pos: 'adj' },
  { id: 585, sv: 'saknar', en: 'miss / lack', pos: 'verb' },
  { id: 586, sv: 'åkte', en: 'went / travelled', pos: 'verb' },
  { id: 587, sv: 'större', en: 'larger / bigger', pos: 'adj' },
  { id: 588, sv: 'vänster', en: 'left (direction)', pos: 'noun' },
  { id: 589, sv: 'kriget', en: 'the war', pos: 'noun' },
  { id: 590, sv: 'familjen', en: 'the family', pos: 'noun' },
  { id: 591, sv: 'rakt', en: 'straight / directly', pos: 'adv' },
  { id: 592, sv: 'dess', en: 'its', pos: 'pronoun' },
  { id: 593, sv: 'behöva', en: 'need / to need', pos: 'verb' },
  { id: 594, sv: 'bör', en: 'should / ought to', pos: 'verb' },
  { id: 595, sv: 'vinna', en: 'win', pos: 'verb' },
  { id: 596, sv: 'skaffa', en: 'get / obtain', pos: 'verb' },
  { id: 597, sv: 'brukar', en: 'usually / tend to', pos: 'verb' },
  { id: 598, sv: 'person', en: 'person', pos: 'noun' },
  { id: 599, sv: 'glömde', en: 'forgot', pos: 'verb' },
  { id: 600, sv: 'frågade', en: 'asked', pos: 'verb' },
  { id: 601, sv: 'låg', en: 'low / lay', pos: 'adj' },
  { id: 602, sv: 'senaste', en: 'latest / most recent', pos: 'adj' },
  { id: 603, sv: 'stod', en: 'stood', pos: 'verb' },
  { id: 604, sv: 'leta', en: 'look for / search', pos: 'verb' },
  { id: 605, sv: 'annorlunda', en: 'different / differently', pos: 'adv' },
  { id: 606, sv: 'tvungen', en: 'forced / have to', pos: 'adj' },
  { id: 607, sv: 'grund', en: 'reason / basis / bottom', pos: 'noun' },
  { id: 608, sv: 'söker', en: 'search / look for', pos: 'verb' },
  { id: 609, sv: 'eget', en: 'own (neuter)', pos: 'adj' },
  { id: 610, sv: 'brukade', en: 'used to', pos: 'verb' },
  { id: 611, sv: 'smart', en: 'smart / clever', pos: 'adj' },
  { id: 612, sv: 'älska', en: 'love', pos: 'verb' },
  { id: 613, sv: 'eld', en: 'fire', pos: 'noun' },
  { id: 614, sv: 'underbart', en: 'wonderful', pos: 'adj' },
  { id: 615, sv: 'sover', en: 'sleep / sleeps', pos: 'verb' },
  { id: 616, sv: 'början', en: 'the beginning', pos: 'noun' },
  { id: 617, sv: 'fred', en: 'peace', pos: 'noun' },
  { id: 618, sv: 'sekunder', en: 'seconds', pos: 'noun' },
  { id: 619, sv: 'fantastiskt', en: 'fantastic / amazing', pos: 'adj' },
  { id: 620, sv: 'ofta', en: 'often', pos: 'adv' },
  { id: 621, sv: 'pojken', en: 'the boy', pos: 'noun' },
  { id: 622, sv: 'vakna', en: 'wake up', pos: 'verb' },
  { id: 623, sv: 'lyssnar', en: 'listen / listens', pos: 'verb' },
  { id: 624, sv: 'dålig', en: 'bad / poor', pos: 'adj' },
  { id: 625, sv: 'kläder', en: 'clothes', pos: 'noun' },
  { id: 626, sv: 'fortsätter', en: 'continue / continues', pos: 'verb' },
  { id: 627, sv: 'rummet', en: 'the room', pos: 'noun' },
  { id: 628, sv: 'höger', en: 'right (direction)', pos: 'noun' },
  { id: 629, sv: 'kropp', en: 'body', pos: 'noun' },
  { id: 630, sv: 'timme', en: 'hour', pos: 'noun' },
  { id: 631, sv: 'öl', en: 'beer', pos: 'noun' },
  { id: 632, sv: 'skada', en: 'injury / damage / harm', pos: 'noun' },
  { id: 633, sv: 'ned', en: 'down', pos: 'adv' },
  { id: 634, sv: 'människa', en: 'human being / person', pos: 'noun' },
  { id: 635, sv: 'telefon', en: 'telephone / phone', pos: 'noun' },
  { id: 636, sv: 'kung', en: 'king', pos: 'noun' },
  { id: 637, sv: 'värld', en: 'world', pos: 'noun' },
  { id: 638, sv: 'farbror', en: 'uncle', pos: 'noun' },
  { id: 639, sv: 'svart', en: 'black', pos: 'adj' },
  { id: 640, sv: 'hår', en: 'hair', pos: 'noun' },
  { id: 641, sv: 'orolig', en: 'worried / anxious', pos: 'adj' },
  { id: 642, sv: 'röra', en: 'move / touch / mess', pos: 'verb' },
  { id: 643, sv: 'lycklig', en: 'happy / lucky', pos: 'adj' },
  { id: 644, sv: 'oj', en: 'oh / wow', pos: 'interjection' },
  { id: 645, sv: 'dansa', en: 'dance', pos: 'verb' },
  { id: 646, sv: 'försiktig', en: 'careful / cautious', pos: 'adj' },
  { id: 647, sv: 'allvar', en: 'seriousness / earnest', pos: 'noun' },
  { id: 648, sv: 'adjö', en: 'goodbye', pos: 'interjection' },
  { id: 649, sv: 'pojkar', en: 'boys', pos: 'noun' },
  { id: 650, sv: 'levande', en: 'alive / living', pos: 'adj' },
  { id: 651, sv: 'naturligtvis', en: 'of course / naturally', pos: 'adv' },
  { id: 652, sv: 'beklagar', en: 'regret / am sorry', pos: 'verb' },
  { id: 653, sv: 'akta', en: 'watch out / beware', pos: 'verb' },
  { id: 654, sv: 'tjejer', en: 'girls', pos: 'noun' },
  { id: 655, sv: 'svar', en: 'answer / reply', pos: 'noun' },
  { id: 656, sv: 'fri', en: 'free', pos: 'adj' },
  { id: 657, sv: 'träffat', en: 'met', pos: 'verb' },
  { id: 658, sv: 'djur', en: 'animal', pos: 'noun' },
  { id: 659, sv: 'särskilt', en: 'especially / particularly', pos: 'adv' },
  { id: 660, sv: 'körde', en: 'drove', pos: 'verb' },
  { id: 661, sv: 'förlorade', en: 'lost', pos: 'verb' },
  { id: 662, sv: 'läkare', en: 'doctor', pos: 'noun' },
  { id: 663, sv: 'nio', en: 'nine', pos: 'numeral' },
  { id: 664, sv: 'döden', en: 'death / the death', pos: 'noun' },
  { id: 665, sv: 'fängelse', en: 'prison', pos: 'noun' },
  { id: 666, sv: 'stark', en: 'strong', pos: 'adj' },
  { id: 667, sv: 'förlora', en: 'lose', pos: 'verb' },
  { id: 668, sv: 'litet', en: 'small / a little', pos: 'adj' },
  { id: 669, sv: 'affärer', en: 'business / shops', pos: 'noun' },
  { id: 670, sv: 'skydda', en: 'protect', pos: 'verb' },
  { id: 671, sv: 'bok', en: 'book', pos: 'noun' },
  { id: 672, sv: 'skickar', en: 'send / sends', pos: 'verb' },
  { id: 673, sv: 'funkar', en: 'work / function (colloquial)', pos: 'verb' },
  { id: 674, sv: 'meter', en: 'metres / meters', pos: 'noun' },
  { id: 675, sv: 'duktig', en: 'good at / skilled / clever', pos: 'adj' },
  { id: 676, sv: 'olika', en: 'different / various', pos: 'adj' },
  { id: 677, sv: 'sälja', en: 'sell', pos: 'verb' },
  { id: 678, sv: 'flickor', en: 'girls', pos: 'noun' },
  { id: 679, sv: 'mark', en: 'land / ground', pos: 'noun' },
  { id: 680, sv: 'fader', en: 'father (formal)', pos: 'noun' },
  { id: 681, sv: 'bevis', en: 'evidence / proof', pos: 'noun' },
  { id: 682, sv: 'berättat', en: 'told / narrated', pos: 'verb' },
  { id: 683, sv: 'kasta', en: 'throw', pos: 'verb' },
  { id: 684, sv: 'tredje', en: 'third', pos: 'numeral' },
  { id: 685, sv: 'stolt', en: 'proud', pos: 'adj' },
  { id: 686, sv: 'stäng', en: 'close / shut', pos: 'verb' },
  { id: 687, sv: 'meddelande', en: 'message', pos: 'noun' },
  { id: 688, sv: 'söt', en: 'sweet / cute', pos: 'adj' },
  { id: 689, sv: 'mord', en: 'murder', pos: 'noun' },
  { id: 690, sv: 'film', en: 'film / movie', pos: 'noun' },
  { id: 691, sv: 'spel', en: 'game', pos: 'noun' },
  { id: 692, sv: 'gatan', en: 'the street', pos: 'noun' },
  { id: 693, sv: 'satte', en: 'put / placed / sat', pos: 'verb' },
  { id: 694, sv: 'underbar', en: 'wonderful', pos: 'adj' },
  { id: 695, sv: 'köpte', en: 'bought', pos: 'verb' },
  { id: 696, sv: 'frun', en: 'the wife', pos: 'noun' },
  { id: 697, sv: 'sjukhuset', en: 'the hospital', pos: 'noun' },
  { id: 698, sv: 'gillade', en: 'liked', pos: 'verb' },
  { id: 699, sv: 'glömma', en: 'forget', pos: 'verb' },
  { id: 700, sv: 'tacka', en: 'thank', pos: 'verb' },
  { id: 701, sv: 'dröm', en: 'dream', pos: 'noun' },
  { id: 702, sv: 'hungrig', en: 'hungry', pos: 'adj' },
  { id: 703, sv: 'ordna', en: 'arrange / sort out', pos: 'verb' },
  { id: 704, sv: 'äntligen', en: 'finally / at last', pos: 'adv' },
  { id: 705, sv: 'dödat', en: 'killed', pos: 'verb' },
  { id: 706, sv: 'intressant', en: 'interesting', pos: 'adj' },
  { id: 707, sv: 'slutet', en: 'the end', pos: 'noun' },
  { id: 708, sv: 'musik', en: 'music', pos: 'noun' },
  { id: 709, sv: 'samtal', en: 'conversation / call', pos: 'noun' },
  { id: 710, sv: 'försiktigt', en: 'carefully / gently', pos: 'adv' },
  { id: 711, sv: 'istället', en: 'instead', pos: 'adv' },
  { id: 712, sv: 'speciellt', en: 'especially / specifically', pos: 'adv' },
  { id: 713, sv: 'nyheter', en: 'news', pos: 'noun' },
  { id: 714, sv: 'barnet', en: 'the child', pos: 'noun' },
  { id: 715, sv: 'förutom', en: 'except / besides', pos: 'prep' },
  { id: 716, sv: 'chef', en: 'boss / manager / head', pos: 'noun' },
  { id: 717, sv: 'ungefär', en: 'about / approximately', pos: 'adv' },
  { id: 718, sv: 'åtminstone', en: 'at least', pos: 'adv' },
  { id: 719, sv: 'fröken', en: 'Miss', pos: 'noun' },
  { id: 720, sv: 'trots', en: 'despite / in spite of', pos: 'prep' },
  { id: 721, sv: 'fest', en: 'party', pos: 'noun' },
  { id: 722, sv: 'stad', en: 'city / town', pos: 'noun' },
  { id: 723, sv: 'skola', en: 'school', pos: 'noun' },
  { id: 724, sv: 'gata', en: 'street', pos: 'noun' },
  { id: 725, sv: 'dörr', en: 'door', pos: 'noun' },
  { id: 726, sv: 'säng', en: 'bed', pos: 'noun' },
  { id: 727, sv: 'mat', en: 'food', pos: 'noun' },
  { id: 728, sv: 'himmel', en: 'sky / heaven', pos: 'noun' },
  { id: 729, sv: 'sol', en: 'sun', pos: 'noun' },
  { id: 730, sv: 'måne', en: 'moon', pos: 'noun' },
  { id: 731, sv: 'stjärna', en: 'star', pos: 'noun' },
  { id: 732, sv: 'hav', en: 'sea / ocean', pos: 'noun' },
  { id: 733, sv: 'träd', en: 'tree', pos: 'noun' },
  { id: 734, sv: 'blomma', en: 'flower', pos: 'noun' },
  { id: 735, sv: 'berg', en: 'mountain', pos: 'noun' },
  { id: 736, sv: 'sjö', en: 'lake', pos: 'noun' },
  { id: 737, sv: 'flod', en: 'river', pos: 'noun' },
  { id: 738, sv: 'vinter', en: 'winter', pos: 'noun' },
  { id: 739, sv: 'sommar', en: 'summer', pos: 'noun' },
  { id: 740, sv: 'höst', en: 'autumn / fall', pos: 'noun' },
  { id: 741, sv: 'vår', en: 'spring', pos: 'noun' },
  { id: 742, sv: 'måndag', en: 'Monday', pos: 'noun' },
  { id: 743, sv: 'tisdag', en: 'Tuesday', pos: 'noun' },
  { id: 744, sv: 'onsdag', en: 'Wednesday', pos: 'noun' },
  { id: 745, sv: 'torsdag', en: 'Thursday', pos: 'noun' },
  { id: 746, sv: 'fredag', en: 'Friday', pos: 'noun' },
  { id: 747, sv: 'lördag', en: 'Saturday', pos: 'noun' },
  { id: 748, sv: 'söndag', en: 'Sunday', pos: 'noun' },
  { id: 749, sv: 'januari', en: 'January', pos: 'noun' },
  { id: 750, sv: 'februari', en: 'February', pos: 'noun' },
  { id: 751, sv: 'mars', en: 'March', pos: 'noun' },
  { id: 752, sv: 'april', en: 'April', pos: 'noun' },
  { id: 753, sv: 'maj', en: 'May', pos: 'noun' },
  { id: 754, sv: 'juni', en: 'June', pos: 'noun' },
  { id: 755, sv: 'juli', en: 'July', pos: 'noun' },
  { id: 756, sv: 'augusti', en: 'August', pos: 'noun' },
  { id: 757, sv: 'september', en: 'September', pos: 'noun' },
  { id: 758, sv: 'oktober', en: 'October', pos: 'noun' },
  { id: 759, sv: 'november', en: 'November', pos: 'noun' },
  { id: 760, sv: 'december', en: 'December', pos: 'noun' },
  { id: 761, sv: 'röd', en: 'red', pos: 'adj' },
  { id: 762, sv: 'blå', en: 'blue', pos: 'adj' },
  { id: 763, sv: 'grön', en: 'green', pos: 'adj' },
  { id: 764, sv: 'gul', en: 'yellow', pos: 'adj' },
  { id: 765, sv: 'vit', en: 'white', pos: 'adj' },
  { id: 766, sv: 'svart', en: 'black', pos: 'adj' },
  { id: 767, sv: 'grå', en: 'grey', pos: 'adj' },
  { id: 768, sv: 'rosa', en: 'pink', pos: 'adj' },
  { id: 769, sv: 'brun', en: 'brown', pos: 'adj' },
  { id: 770, sv: 'orange', en: 'orange', pos: 'adj' },
  { id: 771, sv: 'ett', en: 'one', pos: 'numeral' },
  { id: 772, sv: 'hundra', en: 'hundred', pos: 'numeral' },
  { id: 773, sv: 'tusen', en: 'thousand', pos: 'numeral' },
  { id: 774, sv: 'miljon', en: 'million', pos: 'numeral' },
  { id: 775, sv: 'noll', en: 'zero', pos: 'numeral' },
  { id: 776, sv: 'halv', en: 'half', pos: 'adj' },
  { id: 777, sv: 'dubbel', en: 'double', pos: 'adj' },
  { id: 778, sv: 'tidig', en: 'early', pos: 'adj' },
  { id: 779, sv: 'sen', en: 'late', pos: 'adj' },
  { id: 780, sv: 'ung', en: 'young', pos: 'adj' },
  { id: 781, sv: 'gammal', en: 'old', pos: 'adj' },
  { id: 782, sv: 'stor', en: 'big / large', pos: 'adj' },
  { id: 783, sv: 'liten', en: 'small / little', pos: 'adj' },
  { id: 784, sv: 'lång', en: 'long / tall', pos: 'adj' },
  { id: 785, sv: 'kort', en: 'short', pos: 'adj' },
  { id: 786, sv: 'bred', en: 'wide / broad', pos: 'adj' },
  { id: 787, sv: 'smal', en: 'narrow / slim', pos: 'adj' },
  { id: 788, sv: 'tung', en: 'heavy', pos: 'adj' },
  { id: 789, sv: 'lätt', en: 'light / easy', pos: 'adj' },
  { id: 790, sv: 'varm', en: 'warm / hot', pos: 'adj' },
  { id: 791, sv: 'kall', en: 'cold', pos: 'adj' },
  { id: 792, sv: 'het', en: 'hot', pos: 'adj' },
  { id: 793, sv: 'full', en: 'full / drunk', pos: 'adj' },
  { id: 794, sv: 'tom', en: 'empty', pos: 'adj' },
  { id: 795, sv: 'ren', en: 'clean', pos: 'adj' },
  { id: 796, sv: 'smutsig', en: 'dirty', pos: 'adj' },
  { id: 797, sv: 'snabb', en: 'fast / quick', pos: 'adj' },
  { id: 798, sv: 'långsam', en: 'slow', pos: 'adj' },
  { id: 799, sv: 'hög', en: 'high / tall / loud', pos: 'adj' },
  { id: 800, sv: 'låg', en: 'low', pos: 'adj' },
  { id: 801, sv: 'öppen', en: 'open', pos: 'adj' },
  { id: 802, sv: 'stängd', en: 'closed', pos: 'adj' },
  { id: 803, sv: 'rik', en: 'rich', pos: 'adj' },
  { id: 804, sv: 'fattig', en: 'poor', pos: 'adj' },
  { id: 805, sv: 'farlig', en: 'dangerous', pos: 'adj' },
  { id: 806, sv: 'säker', en: 'safe / sure', pos: 'adj' },
  { id: 807, sv: 'viktig', en: 'important', pos: 'adj' },
  { id: 808, sv: 'möjlig', en: 'possible', pos: 'adj' },
  { id: 809, sv: 'omöjlig', en: 'impossible', pos: 'adj' },
  { id: 810, sv: 'nödvändig', en: 'necessary', pos: 'adj' },
  { id: 811, sv: 'vanlig', en: 'common / ordinary', pos: 'adj' },
  { id: 812, sv: 'ovanlig', en: 'unusual / uncommon', pos: 'adj' },
  { id: 813, sv: 'äta', en: 'eat', pos: 'verb' },
  { id: 814, sv: 'dricka', en: 'drink', pos: 'verb' },
  { id: 815, sv: 'sova', en: 'sleep', pos: 'verb' },
  { id: 816, sv: 'springa', en: 'run', pos: 'verb' },
  { id: 817, sv: 'hoppa', en: 'jump', pos: 'verb' },
  { id: 818, sv: 'simma', en: 'swim', pos: 'verb' },
  { id: 819, sv: 'flyga', en: 'fly', pos: 'verb' },
  { id: 820, sv: 'sjunga', en: 'sing', pos: 'verb' },
  { id: 821, sv: 'skratta', en: 'laugh', pos: 'verb' },
  { id: 822, sv: 'gråta', en: 'cry', pos: 'verb' },
  { id: 823, sv: 'skrika', en: 'scream / shout', pos: 'verb' },
  { id: 824, sv: 'vispa', en: 'whisper', pos: 'verb' },
  { id: 825, sv: 'tänka', en: 'think', pos: 'verb' },
  { id: 826, sv: 'drömma', en: 'dream', pos: 'verb' },
  { id: 827, sv: 'minnas', en: 'remember', pos: 'verb' },
  { id: 828, sv: 'förstå', en: 'understand', pos: 'verb' },
  { id: 829, sv: 'lära sig', en: 'learn', pos: 'verb' },
  { id: 830, sv: 'glömma', en: 'forget', pos: 'verb' },
  { id: 831, sv: 'öppna', en: 'open', pos: 'verb' },
  { id: 832, sv: 'stänga', en: 'close / shut', pos: 'verb' },
  { id: 833, sv: 'köpa', en: 'buy', pos: 'verb' },
  { id: 834, sv: 'sälja', en: 'sell', pos: 'verb' },
  { id: 835, sv: 'betala', en: 'pay', pos: 'verb' },
  { id: 836, sv: 'arbeta', en: 'work', pos: 'verb' },
  { id: 837, sv: 'studera', en: 'study', pos: 'verb' },
  { id: 838, sv: 'undervisa', en: 'teach', pos: 'verb' },
  { id: 839, sv: 'bygga', en: 'build', pos: 'verb' },
  { id: 840, sv: 'bryta', en: 'break', pos: 'verb' },
  { id: 841, sv: 'fixa', en: 'fix / sort out', pos: 'verb' },
  { id: 842, sv: 'rensa', en: 'clean / clear', pos: 'verb' },
  { id: 843, sv: 'laga', en: 'cook / repair', pos: 'verb' },
  { id: 844, sv: 'välja', en: 'choose / select', pos: 'verb' },
  { id: 845, sv: 'bestämma', en: 'decide', pos: 'verb' },
  { id: 846, sv: 'ändra', en: 'change', pos: 'verb' },
  { id: 847, sv: 'börja', en: 'start / begin', pos: 'verb' },
  { id: 848, sv: 'sluta', en: 'stop / quit', pos: 'verb' },
  { id: 849, sv: 'fortsätta', en: 'continue', pos: 'verb' },
  { id: 850, sv: 'vänta', en: 'wait', pos: 'verb' },
  { id: 851, sv: 'förlora', en: 'lose', pos: 'verb' },
  { id: 852, sv: 'hitta', en: 'find', pos: 'verb' },
  { id: 853, sv: 'söka', en: 'search / look for', pos: 'verb' },
  { id: 854, sv: 'fråga', en: 'ask', pos: 'verb' },
  { id: 855, sv: 'svara', en: 'answer', pos: 'verb' },
  { id: 856, sv: 'berätta', en: 'tell', pos: 'verb' },
  { id: 857, sv: 'förklara', en: 'explain', pos: 'verb' },
  { id: 858, sv: 'visa', en: 'show', pos: 'verb' },
  { id: 859, sv: 'dölja', en: 'hide', pos: 'verb' },
  { id: 860, sv: 'skydda', en: 'protect', pos: 'verb' },
  { id: 861, sv: 'attackera', en: 'attack', pos: 'verb' },
  { id: 862, sv: 'försvara', en: 'defend', pos: 'verb' },
  { id: 863, sv: 'vinna', en: 'win', pos: 'verb' },
  { id: 864, sv: 'förlora', en: 'lose', pos: 'verb' },
  { id: 865, sv: 'dela', en: 'share / divide', pos: 'verb' },
  { id: 866, sv: 'samla', en: 'collect / gather', pos: 'verb' },
  { id: 867, sv: 'skicka', en: 'send', pos: 'verb' },
  { id: 868, sv: 'ta emot', en: 'receive', pos: 'verb' },
  { id: 869, sv: 'bära', en: 'carry / wear', pos: 'verb' },
  { id: 870, sv: 'lyfta', en: 'lift', pos: 'verb' },
  { id: 871, sv: 'tappa', en: 'drop / lose', pos: 'verb' },
  { id: 872, sv: 'kasta', en: 'throw', pos: 'verb' },
  { id: 873, sv: 'fånga', en: 'catch', pos: 'verb' },
  { id: 874, sv: 'trycka', en: 'press / push', pos: 'verb' },
  { id: 875, sv: 'dra', en: 'pull', pos: 'verb' },
  { id: 876, sv: 'knyta', en: 'tie / knot', pos: 'verb' },
  { id: 877, sv: 'skära', en: 'cut', pos: 'verb' },
  { id: 878, sv: 'måla', en: 'paint', pos: 'verb' },
  { id: 879, sv: 'rita', en: 'draw', pos: 'verb' },
  { id: 880, sv: 'räkna', en: 'count', pos: 'verb' },
  { id: 881, sv: 'mäta', en: 'measure', pos: 'verb' },
  { id: 882, sv: 'väga', en: 'weigh', pos: 'verb' },
  { id: 883, sv: 'jämföra', en: 'compare', pos: 'verb' },
  { id: 884, sv: 'känna igen', en: 'recognise', pos: 'verb' },
  { id: 885, sv: 'tillhöra', en: 'belong to', pos: 'verb' },
  { id: 886, sv: 'bero på', en: 'depend on', pos: 'verb' },
  { id: 887, sv: 'hända', en: 'happen', pos: 'verb' },
  { id: 888, sv: 'fungera', en: 'work / function', pos: 'verb' },
  { id: 889, sv: 'existera', en: 'exist', pos: 'verb' },
  { id: 890, sv: 'förändra', en: 'change / alter', pos: 'verb' },
  { id: 891, sv: 'förbättra', en: 'improve', pos: 'verb' },
  { id: 892, sv: 'försämra', en: 'worsen', pos: 'verb' },
  { id: 893, sv: 'öka', en: 'increase', pos: 'verb' },
  { id: 894, sv: 'minska', en: 'decrease / reduce', pos: 'verb' },
  { id: 895, sv: 'stanna', en: 'stop / stay', pos: 'verb' },
  { id: 896, sv: 'röra sig', en: 'move', pos: 'verb' },
  { id: 897, sv: 'resa', en: 'travel', pos: 'verb' },
  { id: 898, sv: 'återvända', en: 'return', pos: 'verb' },
  { id: 899, sv: 'anlända', en: 'arrive', pos: 'verb' },
  { id: 900, sv: 'lämna', en: 'leave', pos: 'verb' },
  { id: 901, sv: 'hälsa', en: 'greet', pos: 'verb' },
  { id: 902, sv: 'le', en: 'smile', pos: 'verb' },
  { id: 903, sv: 'krama', en: 'hug', pos: 'verb' },
  { id: 904, sv: 'kyssa', en: 'kiss', pos: 'verb' },
  { id: 905, sv: 'slåss', en: 'fight', pos: 'verb' },
  { id: 906, sv: 'skydda', en: 'protect', pos: 'verb' },
  { id: 907, sv: 'följa med', en: 'come along / accompany', pos: 'verb' },
  { id: 908, sv: 'hålla med', en: 'agree', pos: 'verb' },
  { id: 909, sv: 'hålla med', en: 'agree', pos: 'verb' },
  { id: 910, sv: 'bråka', en: 'argue / quarrel', pos: 'verb' },
  { id: 911, sv: 'förlåta', en: 'forgive', pos: 'verb' },
  { id: 912, sv: 'tacka', en: 'thank', pos: 'verb' },
  { id: 913, sv: 'be om ursäkt', en: 'apologise', pos: 'verb' },
  { id: 914, sv: 'be', en: 'ask / pray', pos: 'verb' },
  { id: 915, sv: 'erbjuda', en: 'offer', pos: 'verb' },
  { id: 916, sv: 'acceptera', en: 'accept', pos: 'verb' },
  { id: 917, sv: 'neka', en: 'refuse / deny', pos: 'verb' },
  { id: 918, sv: 'tillåta', en: 'allow / permit', pos: 'verb' },
  { id: 919, sv: 'förbjuda', en: 'forbid / ban', pos: 'verb' },
  { id: 920, sv: 'kräva', en: 'require / demand', pos: 'verb' },
  { id: 921, sv: 'välja', en: 'choose', pos: 'verb' },
  { id: 922, sv: 'planera', en: 'plan', pos: 'verb' },
  { id: 923, sv: 'förbereda', en: 'prepare', pos: 'verb' },
  { id: 924, sv: 'avsluta', en: 'finish / complete', pos: 'verb' },
  { id: 925, sv: 'kontrollera', en: 'check / control', pos: 'verb' },
  { id: 926, sv: 'hantera', en: 'handle / manage', pos: 'verb' },
  { id: 927, sv: 'använda', en: 'use', pos: 'verb' },
  { id: 928, sv: 'skapa', en: 'create', pos: 'verb' },
  { id: 929, sv: 'förstöra', en: 'destroy', pos: 'verb' },
  { id: 930, sv: 'rädda', en: 'save / rescue', pos: 'verb' },
  { id: 931, sv: 'hjälpa', en: 'help', pos: 'verb' },
  { id: 932, sv: 'störa', en: 'disturb / bother', pos: 'verb' },
  { id: 933, sv: 'imponera', en: 'impress', pos: 'verb' },
  { id: 934, sv: 'inspirera', en: 'inspire', pos: 'verb' },
  { id: 935, sv: 'motivera', en: 'motivate', pos: 'verb' },
  { id: 936, sv: 'uppmuntra', en: 'encourage', pos: 'verb' },
  { id: 937, sv: 'varna', en: 'warn', pos: 'verb' },
  { id: 938, sv: 'hotas', en: 'threaten', pos: 'verb' },
  { id: 939, sv: 'lova', en: 'promise', pos: 'verb' },
  { id: 940, sv: 'ljuga', en: 'lie (tell a lie)', pos: 'verb' },
  { id: 941, sv: 'berätta', en: 'tell / narrate', pos: 'verb' },
  { id: 942, sv: 'diskutera', en: 'discuss', pos: 'verb' },
  { id: 943, sv: 'argumentera', en: 'argue', pos: 'verb' },
  { id: 944, sv: 'övertyga', en: 'convince', pos: 'verb' },
  { id: 945, sv: 'komma ihåg', en: 'remember', pos: 'verb' },
  { id: 946, sv: 'glömma bort', en: 'forget', pos: 'verb' },
  { id: 947, sv: 'inse', en: 'realise', pos: 'verb' },
  { id: 948, sv: 'märka', en: 'notice', pos: 'verb' },
  { id: 949, sv: 'uppfatta', en: 'perceive', pos: 'verb' },
  { id: 950, sv: 'anta', en: 'assume', pos: 'verb' },
  { id: 951, sv: 'misstänka', en: 'suspect', pos: 'verb' },
  { id: 952, sv: 'bevisa', en: 'prove', pos: 'verb' },
  { id: 953, sv: 'lösa', en: 'solve', pos: 'verb' },
  { id: 954, sv: 'misslyckas', en: 'fail', pos: 'verb' },
  { id: 955, sv: 'lyckas', en: 'succeed', pos: 'verb' },
  { id: 956, sv: 'överleva', en: 'survive', pos: 'verb' },
  { id: 957, sv: 'kämpa', en: 'fight / struggle', pos: 'verb' },
  { id: 958, sv: 'ge upp', en: 'give up', pos: 'verb' },
  { id: 959, sv: 'hålla fast', en: 'hold on', pos: 'verb' },
  { id: 960, sv: 'tappa hoppet', en: 'lose hope', pos: 'verb' },
  { id: 961, sv: 'hoppas', en: 'hope', pos: 'verb' },
  { id: 962, sv: 'önska', en: 'wish', pos: 'verb' },
  { id: 963, sv: 'längta', en: 'long for / yearn', pos: 'verb' },
  { id: 964, sv: 'sakna', en: 'miss', pos: 'verb' },
  { id: 965, sv: 'älska', en: 'love', pos: 'verb' },
  { id: 966, sv: 'hata', en: 'hate', pos: 'verb' },
  { id: 967, sv: 'frukta', en: 'fear', pos: 'verb' },
  { id: 968, sv: 'njuta av', en: 'enjoy', pos: 'verb' },
  { id: 969, sv: 'uppskatta', en: 'appreciate', pos: 'verb' },
  { id: 970, sv: 'lita på', en: 'trust', pos: 'verb' },
  { id: 971, sv: 'respektera', en: 'respect', pos: 'verb' },
  { id: 972, sv: 'bry sig om', en: 'care about', pos: 'verb' },
  { id: 973, sv: 'bero på', en: 'depend on', pos: 'verb' },
  { id: 974, sv: 'koncentrera sig', en: 'concentrate', pos: 'verb' },
  { id: 975, sv: 'ta hand om', en: 'take care of', pos: 'verb' },
  { id: 976, sv: 'passa på', en: 'take the opportunity', pos: 'verb' },
  { id: 977, sv: 'ge sig', en: 'give in / set off', pos: 'verb' },
  { id: 978, sv: 'stämma', en: 'be correct / match', pos: 'verb' },
  { id: 979, sv: 'räcka', en: 'be enough / reach', pos: 'verb' },
  { id: 980, sv: 'skilja sig', en: 'differ / divorce', pos: 'verb' },
  { id: 981, sv: 'gälla', en: 'apply / concern', pos: 'verb' },
  { id: 982, sv: 'hända', en: 'happen', pos: 'verb' },
  { id: 983, sv: 'ske', en: 'happen / occur', pos: 'verb' },
  { id: 984, sv: 'uppstå', en: 'arise', pos: 'verb' },
  { id: 985, sv: 'försvinna', en: 'disappear', pos: 'verb' },
  { id: 986, sv: 'dyka upp', en: 'appear / show up', pos: 'verb' },
  { id: 987, sv: 'ta slut', en: 'run out / end', pos: 'verb' },
  { id: 988, sv: 'börja om', en: 'start over', pos: 'verb' },
  { id: 989, sv: 'hålla på', en: 'be doing / keep on', pos: 'verb' },
  { id: 990, sv: 'se till', en: 'make sure', pos: 'verb' },
  { id: 991, sv: 'ta sig', en: 'get (somewhere)', pos: 'verb' },
  { id: 992, sv: 'klara sig', en: 'manage / get by', pos: 'verb' },
  { id: 993, sv: 'passa', en: 'suit / fit', pos: 'verb' },
  { id: 994, sv: 'räcka till', en: 'be sufficient', pos: 'verb' },
  { id: 995, sv: 'strunta i', en: 'ignore / not care about', pos: 'verb' },
  { id: 996, sv: 'se fram emot', en: 'look forward to', pos: 'verb' },
  { id: 997, sv: 'ta itu med', en: 'deal with', pos: 'verb' },
  { id: 998, sv: 'komma överens', en: 'get along / agree', pos: 'verb' },
  { id: 999, sv: 'hålla koll på', en: 'keep track of', pos: 'verb' },
  { id: 1000, sv: 'lycka till', en: 'good luck', pos: 'interjection' },
]
